// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/charliego3/pallas"
)

// Injectors from wire.go:

func CreateApplication() *pallas.Application {
	v := appOpts()
	application := pallas.NewApp(v...)
	return application
}
