// Code generated by protoc-gen-pallas-http. DO NOT EDIT.
//
// proto-gen-pallas-http version: 1.0.0
// protoc version: v4.25.0
// source file: protos/greet.proto

package pb

import (
	types "github.com/charliego3/pallas/types"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the pallas package it is being compiled against.
var _ = new(types.Service)

type UnimplementedGreeterDescServer struct {
	UnimplementedGreeterServer
}

func (UnimplementedGreeterDescServer) Desc() types.ServiceDesc {
	return types.ServiceDesc{
		Grpc: Greeter_ServiceDesc,
		Http: types.HttpServiceDesc{
			ServiceName: "",
			HandlerType: nil,
			Methods: []types.HttpMethodDesc{
				{
					Method:   "GET",
					Template: "/sayHello",
					Handler:  _Greeter_SayHello_GET_HTTP_Handler,
				},
			},
		},
	}
}
