// Code generated by protoc-gen-pallas-http. DO NOT EDIT.
//
// proto-gen-pallas-http version: 1.0.0
// protoc version: v4.25.2
// source file: protos/user.proto

package pb

import (
	types "github.com/charliego3/pallas/types"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the pallas package it is being compiled against.
var _ = new(types.Service)

type UnimplementedUserDescServer struct {
	UnimplementedUserServer
}

func (UnimplementedUserDescServer) Desc() types.ServiceDesc {
	return types.ServiceDesc{
		Grpc: User_ServiceDesc,
		Http: types.HttpServiceDesc{
			ServiceName: "",
			HandlerType: nil,
			Methods: []types.HttpMethodDesc{
				{
					Method:   "POST",
					Template: "/user/register",
					Handler:  _User_Register_POST_HTTP_Handler,
				},
				{
					Method:   "POST",
					Template: "/user/login",
					Handler:  _User_Login_POST_HTTP_Handler,
				},
			},
		},
	}
}
